#!/bin/sh
# debian/config script for the gitolite package
# Copyright 2010 by Gerfried Fuchs <rhonda@debian.at>
# Licenced under WTFPLv2

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# ask for user to create
db_input low gitolite/gituser || true
db_go

# ask for repository root directory to use
db_input low gitolite/gitdir || true
db_go

# ask for key of admin user (either file or direct input)
db_set gitolite/adminkey ""
db_input low gitolite/adminkey || true
db_go

exit 0
