#!/bin/sh
# wrapper script for gl-setup
# Copyright (C) 2010 Gerfried Fuchs <rhonda@deb.at>
# Licenced under WTFPLv2

PATH=/usr/share/gitolite:$PATH
export PATH

exec /usr/share/gitolite/gl-setup "$@"
