#!/bin/sh
# postrm script for gitolite
# Copyright 2010 by Gerfried Fuchs <rhonda@debian.at>
# Licenced under WTFPLv2

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

action=$1
version=$2


if [ "$action" = "purge" ]; then
	GITUSER="gitolite"

	if [ -e /usr/share/debconf/confmodule ]; then
		. /usr/share/debconf/confmodule

		db_get gitolite/gituser
		GITUSER="${RET:-gitolite}"

		db_purge
	fi

	if which deluser >/dev/null ; then
		deluser --quiet "$GITUSER" >/dev/null || true
		delgroup --quiet "$GITUSER" >/dev/null || true
	fi

fi


exit 0
